# -*- mode: python ; coding: utf-8 -*-
import sys
import os
from pathlib import Path

ROOT = Path(os.path.abspath(os.path.dirname(SPECPATH)))
sys.path.insert(0, str(ROOT))

a = Analysis(
    ['server/app.py'],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        ('prompts/*.txt', 'prompts'),
        ('config/image_presets.json', 'config'),
        ('orchestrator_router.txt', '.'),
    ],
    hiddenimports=[
        'server.routes.projects',
        'server.routes.settings',
        'server.routes.creation',
        'server.routes.gen',
        'server.routes.prompt_gen',
        'server.ws_manager',
        'server.async_orch',
        'server.schemas',
        'core.project_manager',
        'core.style_config',
        'core.workflow_loader',
        'core.agent_factory',
        'core.content_validator',
        'core.continuity',
        'core.qc_gates',
        'core.chunk_strategy',
        'core.bible_updater',
        'core.summary_extractor',
        'core.visual_bible',
        'core.novel_bible',
        'core.image_pipeline',
        'core.orchestrator_base',
        'core.asset_manager',
        'core.cli',
        'core.back_to_menu',
        'agents.orchestrator',
        'agents.outline_designer',
        'agents.plot_expander',
        'agents.screenplay_writer',
        'agents.storyboarder',
        'agents.visual_extractor',
        'agents.prompt_factory',
        'agents.image_preparator',
        'agents.image_artist',
        'agents.image_demand_analyzer',
        'agents.video_producer',
        'tools.api_caller',
        'tools.constants',
        'tools.content_splitter',
        'tools.duration_validator',
        'tools.file_ops',
        'tools.image_api',
        'tools.image_api_openai_compat',
        'tools.image_api_seedream',
        'tools.image_composer',
        'tools.model_registry',
        'tools.video_api',
        'tools.video_api_kling',
        'tools.video_api_luma',
        'tools.video_api_pika',
        'tools.video_api_runway',
        'tools.video_api_seedance',
        'tools.video_concat',
        'llm.backends',
        'llm.client',
        'uvicorn.loops.auto',
        'uvicorn.protocols.http.auto',
        'websockets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'pandas', 'numpy', 'scipy',
        'PIL', 'Pillow', 'sqlalchemy', 'sqlite3',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
